version: "3.9"

services:
  reverse-proxy:
    build:
      context: ../../src/projects/reverse-proxy
    ports:
      - 80:80
    restart: always
    depends_on:
      - web
      - cms
      - mibs
      - keycloak

  web:
    build:
      context: ../../src
      dockerfile: projects/web/Dockerfile
    expose:
      - 80

  cms:
    build:
      context: ../../src
      dockerfile: projects/cms/Dockerfile
    expose:
      - 80

  mibs:
    build:
      context: ../../src
      dockerfile: projects/mibs/Dockerfile
    environment:
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_MIBS_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    expose:
      - 80

  postgres:
    build:
      context: ../../src/projects/postgres-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_KEYCLOAK_DATABASE}
      POSTGRES_MIBS_DB: ${DB_MIBS_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5432

  keycloak:
    build:
      context: ../../src/projects/keycloak
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_KEYCLOAK_DATABASE}
      DB_USER: ${DB_USER}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    depends_on:
      - postgres
    expose:
      - 8080

  smtp-dev:
    build:
      context: ../../src/projects/smtp-dev
    environment:
      MAILNAME: smtp-dev
    expose:
      - 25
      
volumes:
  postgres_data:
    driver: local
