version: "3.9"

services: 
  reverse-proxy:
    build: 
      context: src/projects/reverse-proxy
    ports: 
      - 80:80
    restart: always
    depends_on:
      # - web
      - cms
      - mibs
  
  # web:
  #   build: 
  #     context: src/projects/web
  #   expose:
  #     - 80

  cms:
    build: 
      context: src/projects/cms
    expose:
      - 80

  mibs:
    build: 
      context: src/projects/mibs
    environment:
      DB_DATABASE: mibs
      DB_USER: admin
      DB_PASSWORD: password
    expose:
      - 80
  
  postgres:
    build:
      context: src/projects/postgres-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    expose:
      - 5432

  keycloak:
    build:
      context: src/projects/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: auth
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: cmpt371
    depends_on: 
      - postgres
    ports:
      - 8080:8080

volumes:
  postgres_data:
    driver: local
