version: "3.9"

services: 
  reverse-proxy:
    build: 
      context: src/projects/reverse-proxy
    ports: 
      - 80:80
    restart: always
    depends_on:
      # - web
      - cms
      - mibs

  # web:
  #   build: 
  #     context: src/projects/web
  #   expose:
  #     - 80

  cms:
    build: 
      context: src/projects/cms
    expose:
      - 80

  mibs:
    build: 
      context: src/projects/mibs
    expose:
      - 80