name: artifacts cleanup
on:
  workflow_dispatch:
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'
